#Do not add Deploy Stage **SKIP Deploy STAGE**

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - rm -rf node_modules
      - npm cache clean --force


  build:
    commands:
      - echo Running build commands...
      - npm install --force # Install dependencies
      - npm install ajv ajv-keywords
      - npm run build  # Run build script

  post_build:
    commands:
      - echo Running post-build commands...
      - aws s3 sync build/ s3://ravat.ravat.com
      - #add cloudfront


      # - export MY_SECRET=$(aws secretsmanager get-secret-value --secret-id your-secret-id --query SecretString --output text)
      # - echo $MY_SECRET > .env # Save the secret to an .env file or export directly
      # - npm run build  # Run build script with the secret
