#Put this file in realtime code so it can come with git

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React application...
      - npm run build
  post_build:
    commands:
      - echo Build completed.
      - echo Copying files to S3...
      - aws s3 sync build/ s3://dashboard.ticketjockey.co 
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id your-distribution-id --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build
